app:
  edit_interval: 1s

service:
  host:  0.0.0.0
  grpc_port: 50051
  http_port: 8084

db_shards:
  - host: comments-shard-1
    port: 5432
    user: comments-user-1
    password: comments-password-1
    db_name: comments_db
    shard_id: 1

  - host: comments-shard-2
    port: 5432
    user: comments-user-2
    password: comments-password-2
    db_name: comments_db
    shard_id: 2
